### ISSUE TITLE
Completar tarea 1

### ISSUE THREAD

**Issue by DrJoseGallardo** [GenomicsEducation/Jacqueline-Vasquez#1]
Estimado alumna, favor completar la tarea 1 de la semana pasada. Respecto de la tarea 2 de esta semana favor incluir un directorio llamado SCRIPT y en almacenar los script.sh elaborados en clase.

**Comment by Jacke07** [comment]
Profesor podría por favor revisar me README y entregarme una retroalimentación de cosas que me falten.
En cuanto al directorio llamado SCRIPT, se refiere a subir pantallazos de cada uno ??
